# Site settings
title: ONDEMANDENV.dev
description: On-Demand Environments and Service Contract Management in Distributed Systems
url: "https://ondemandenv.dev"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages compatible settings
safe: true
source: .
destination: ./_site
incremental: false
gist:
  noscript: false

# Kramdown settings
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Default front matter
defaults:
  - scope:
      path: "articles"
      type: "pages"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .git
  - .gitignore
  - tmp/

# SEO and feed settings
author: ONDEMANDENV
twitter:
  username: ondemandenv
social:
  name: ONDEMANDENV
  links:
    - https://github.com/ondemandenv

# Sitemap settings
sitemap:
  priority: 1.0
  changefreq: 'monthly'
  lastmod: 2025-01-29 